apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  DISCORD_TOKEN: <sample>
  DISCORD_APPLICATION_ID: <sample>
  DISCORD_GUILD_ID: <sample>
  GOOGLE_AUTH_EMAIL: <sample>
  GOOGLE_AUTH_KEY: |
    <sample>
  GOOGLE_SHEETS_DOC_ID: <sample>
  DB_USER: <sample>
  DB_PASSWORD: <sample>
  DB_NAME: <sample>
