apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:AZyUVoUxNU8ekuElGiw=,iv:uzrIrc6A9mcKeSP62+3NqPe6RtvG//tgnhJaUuX35uw=,tag:GJtFza0LZjxzXkesn1XKmg==,type:str]
sops:
  age:
    - recipient: age1feyt5xfrhkz32pudpe664d6f3ut2dk4luqf7rhqgn4tmwqzq03pqfa0p9k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaG9US1dZeGU3c0w2Z09O
        L3Zsbk9EeU91RnZpRFBmd3FUTXNYVE5kdHpNCk9JK3pYcFhIMEdTMXJVNFRqTWIz
        c05sRFV4YzBGbnh1eEd2T3hWalp0SncKLS0tIE1iRm5IVG1Tb2M2ei9kUjhVNU81
        dGY2ZFFNYkN2S0ordmZkaFRVbjJTVzgKwa7ivkmBWc33ty73YWaTOTdAE2S/qp2b
        Jm6BCeEQietMFdUzwFgxCzvFC4fFtCGXi6yc/kadeXWLTQ8OulpVIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T15:21:51Z"
  mac: ENC[AES256_GCM,data:6yZyvaX1IqrtbAEzVuwqPZKsMVWwVyo3XGuIt1xbl90RbgUEeNFsbC4uYTu8mBbqonLNZLgaAACq8TAX9HFFn2zv907+WDB367oZChJUCEvUgJxvTW7aio+WbzELzascC1vkZe44pCiOa/+6R1REti2NTJqKy60HcWyUtj2bjLs=,iv:LbYj2goj6T5cIAt5+d3pyzeEPInse0CRlOpoQ/jQAWM=,tag:L1LvakHvMlghZfUQkn34Mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
