apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# On inclut les bases qu'on veut déployer
resources:
  - ../../base/postgres
  - ../../base/api
  - ../../base/discord
  - ../../base/cert-manager

# Ici, on pourra ajouter des patches plus tard 
# (ex: changer le nombre de réplicas juste pour la prod)
