apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-
commonLabels:
  environment: dev

resources:
  - namespace.yaml
  - ../../base/postgres
  - ../../base/api
  - ../../base/discord
  - ../../base/cert-manager

patches:
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-deployment
      spec:
        template:
          spec:
            containers:
              - name: api
                image: furby-api:local
                imagePullPolicy: Never
                env:
                  - name: DB_HOST
                    value: dev-postgres

  - target:
      kind: Deployment
      name: bot-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: bot-deployment
      spec:
        template:
          spec:
            containers:
              - name: bot
                image: furby-bot:local
                imagePullPolicy: Never

  - target:
      kind: ConfigMap
      name: api-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: api-config
      data:
        DB_HOST: dev-postgres

  - target:
      kind: Ingress
      name: api-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: api-ingress
      spec:
        rules:
          - host: furby-dev.olyxz16.fr
        tls: []
