apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-
commonLabels:
  environment: dev

resources:
  - ../../base/postgres
  - ../../base/api
  - ../../base/discord
  - ../../base/cert-manager

patches:
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-deployment
      spec:
        template:
          spec:
            containers:
              - name: api
                image: furby-api:local
                imagePullPolicy: Never

  - target:
      kind: Deployment
      name: bot-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: bot-deployment
      spec:
        template:
          spec:
            containers:
              - name: bot
                image: furby-bot:local
                imagePullPolicy: Never
