apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  labels:
    app: furby-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: furby-bot
  template:
    metadata:
      labels:
        app: furby-bot
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: bot
          image: ghcr.io/olyxz16/furby/bot:latest
          envFrom:
            - configMapRef:
                name: bot-config
            - secretRef:
                name: bot-secret
